# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define :nodejs do |t|
  config.vm.synced_folder "/work/code", "/app/"
  end

  config.vm.network :forwarded_port, guest: 9000, host: 9000
  config.vm.network :forwarded_port, guest: 9100, host: 9100

  config.vm.provider :virtualbox do |vb|
    vb.name = "nodejs"
    vb.customize ["modifyvm", :id, "--cpus", "1", "--memory", 512]
  end

  config.vm.box = "opscode-ubuntu-12.04-chef11"
  config.vm.box_url = "https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.0.box"

  config.berkshelf.enabled = true
  
  config.vm.provision :shell, :inline => "sudo apt-get update -y"
  config.vm.provision :shell, :inline => "sudo locale-gen fi_FI.UTF-8"
  
  config.vm.provision :chef_solo do |chef|
    chef.log_level = :debug
    chef.add_recipe "apt"
    chef.add_recipe "locales"
    chef.add_recipe "git"
    chef.add_recipe "vim"
    chef.add_recipe "curl"
    chef.add_recipe "nodejs"
  
    chef.json = {
      :locales => {
        :available => "fi_FI.utf8",
        :default => "fi_FI.utf8"
      },
      :nodejs => {
        :install_method => "package",
        :version => "0.10.18"
      }
    }

  end

  config.vm.provision :shell, :inline => "sudo apt-get install libfontconfig -y"
  config.vm.provision :shell, :inline => "sudo apt-get install ruby1.9.3 ruby-compass -y"
  config.vm.provision :shell, :inline => "sudo npm install -g yo grunt-cli bower phantomjs"

end